AllCops:
  NewCops: enable
Documentation:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation
Layout/BeginEndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_line
Layout/BlockAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_block
Layout/BlockEndNewline:
  Enabled: true
Layout/CaseIndentation:
  Enabled: true
Layout/FirstArgumentIndentation:
  Enabled: true
  EnforcedStyle: consistent_relative_to_receiver
Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: special_inside_parentheses
Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: special_inside_parentheses
Layout/HashAlignment:
  Enabled: true
  EnforcedColonStyle: table
Layout/MultilineHashBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical
Layout/MultilineHashKeyLineBreaks:
  Enabled: true
Lint/MissingCopEnableDirective:
  Enabled: false
Metrics/AbcSize:
  Max: 60
Metrics/BlockLength:
  Max: 40
Metrics/BlockNesting:
  Max: 4
Metrics/ClassLength:
  Max: 1500
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/MethodLength:
  Max: 50
Metrics/ModuleLength:
  Max: 500
Metrics/ParameterLists:
  Max: 5
Metrics/PerceivedComplexity:
  Max: 15
Security/Open:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: nested
Style/MapToHash:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
